### ISSUE TITLE
希望能配合网页端完成重新评测时跳过恶意代码的功能

### ISSUE THREAD

**Issue by codgician** [CDFLS/cwoj_daemon#5]
目前网页端在solution表中新增了一名为malicious的纵列，属性为tinyint，长度为1。当其值为0是代表该代码为安全代码，当值为1是代表该代码为恶意代码。而daemon在重新评测过程中应该跳过恶意代码。

希望您有时间能为在database.cpp中将与重新评测有关的MySQL语句加上限制条件 where malicious=0 （仅获取安全代码以重评），并且给插入用户提交代码的MySQL语句加上malicious=0。

当然，在未来如果daemon实现了鉴别用户提交的代码也可以在拒绝评测恶意代码或编译超时代码的同时设置其malicious=1。

谢谢合作！

**Comment by xiawenke** [comment]
这需要关于恶意代码的一些特征
理论上来说用正则表达式把恶意代码过滤出来 删掉或跳过什么的 最后处理

**Comment by codgician** [comment]
目前是网页端可以手动标记一份代码为恶意代码。。。

**Comment by xiawenke** [comment]
所以目前还缺什么 我怎么没懂
